# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
