# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_price_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_page_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_profile_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ig_profile_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_price_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tw_profile_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Photographer'), (2, 'Service Provider'), (3, 'Customer'), (4, 'Explore Mode')], default=4, verbose_name='user type'),
        ),
    ]
