# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20161227_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
    ]
